import { Template } from '../types/canvas';

export const TEMPLATES: Template[] = [
  // 01 — Luxury Fashion Campaign
  {
    id: 'tpl-01',
    title: 'Luxury Fashion Campaign',
    category: 'fashion',
    tags: ['Luxury Brand', 'Fashion', 'Poster', 'Haute Couture'],
    width: 1200,
    height: 1600,
    isPremium: true,
    isTrending: true,
    background: {
      type: 'dark-luxury',
      color: '#0a0a0d',
      secondaryColor: 'rgba(197, 160, 89, 0.15)',
    },
    elements: [
      {
        id: 'el-01-bg-border',
        name: 'Gold Border Frame',
        type: 'shape',
        shapeType: 'rectangle',
        x: 40,
        y: 40,
        width: 1120,
        height: 1520,
        rotation: 0,
        opacity: 0.7,
        zIndex: 1,
        locked: false,
        hidden: false,
        fill: 'transparent',
        strokeColor: '#c5a059',
        strokeWidth: 2,
      },
      {
        id: 'el-01-img',
        name: 'Couture Editorial Model',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=80',
        x: 150,
        y: 260,
        width: 900,
        height: 900,
        rotation: 0,
        opacity: 0.92,
        zIndex: 2,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 16,
        filters: { brightness: 105, contrast: 110, saturation: 90, blur: 0, grayscale: 0, duotoneEnabled: false },
        shadow: { enabled: true, color: 'rgba(0,0,0,0.6)', blur: 30, offsetX: 0, offsetY: 15 },
      },
      {
        id: 'el-01-season',
        name: 'Season Label',
        type: 'text',
        text: 'AUTUMN / WINTER 2027 COLLECTION',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 18,
        fontWeight: 600,
        textAlign: 'center',
        letterSpacing: 6,
        lineHeight: 1.2,
        color: '#c5a059',
        x: 100,
        y: 110,
        width: 1000,
        height: 30,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
        textTransform: 'uppercase',
      },
      {
        id: 'el-01-title',
        name: 'Brand Headline',
        type: 'text',
        text: 'L’ÉLÉGANCE OBSIDIENNE',
        fontFamily: "'Cinzel', serif",
        fontSize: 58,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 8,
        lineHeight: 1.15,
        color: '#ffffff',
        x: 80,
        y: 150,
        width: 1040,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 4,
        locked: false,
        hidden: false,
        textTransform: 'uppercase',
      },
      {
        id: 'el-01-badge',
        name: 'Edition Badge',
        type: 'shape',
        shapeType: 'pill',
        x: 460,
        y: 1200,
        width: 280,
        height: 52,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        locked: false,
        hidden: false,
        fill: '#c5a059',
      },
      {
        id: 'el-01-badge-text',
        name: 'Badge CTA',
        type: 'text',
        text: 'DISCOVER RUNWAY',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 14,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 3,
        lineHeight: 1,
        color: '#0a0a0d',
        x: 460,
        y: 1218,
        width: 280,
        height: 30,
        rotation: 0,
        opacity: 1,
        zIndex: 6,
        locked: false,
        hidden: false,
        textTransform: 'uppercase',
      },
      {
        id: 'el-01-footer',
        name: 'Location Footer',
        type: 'text',
        text: 'PARIS • MILAN • NEW YORK • TOKYO',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 15,
        fontWeight: 500,
        textAlign: 'center',
        letterSpacing: 5,
        lineHeight: 1.2,
        color: '#8b8a91',
        x: 100,
        y: 1460,
        width: 1000,
        height: 30,
        rotation: 0,
        opacity: 0.8,
        zIndex: 7,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 02 — Dark Luxury Brand
  {
    id: 'tpl-02',
    title: 'Dark Luxury Brand',
    category: 'luxury-brand',
    tags: ['Luxury Brand', 'Instagram Post', 'Minimalist'],
    width: 1080,
    height: 1080,
    isPremium: true,
    isNew: true,
    background: {
      type: 'dark-luxury',
      color: '#08080a',
      secondaryColor: 'rgba(255,255,255,0.03)',
    },
    elements: [
      {
        id: 'el-02-rect',
        name: 'Monolith Card',
        type: 'shape',
        shapeType: 'rectangle',
        x: 90,
        y: 90,
        width: 900,
        height: 900,
        rotation: 0,
        opacity: 0.6,
        zIndex: 1,
        locked: false,
        hidden: false,
        fill: '#121217',
        strokeColor: 'rgba(255,255,255,0.1)',
        strokeWidth: 1,
        borderRadius: 24,
      },
      {
        id: 'el-02-img',
        name: 'Artisan Perfume Bottle',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1000&q=80',
        x: 290,
        y: 200,
        width: 500,
        height: 520,
        rotation: 0,
        opacity: 0.95,
        zIndex: 2,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 16,
        filters: { brightness: 100, contrast: 115, saturation: 70, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-02-sub',
        name: 'Product Moniker',
        type: 'text',
        text: 'N° 07 • EXTRAIT DE PARFUM',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 14,
        fontWeight: 600,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1.2,
        color: '#d4af37',
        x: 100,
        y: 760,
        width: 880,
        height: 25,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-02-title',
        name: 'Headline',
        type: 'text',
        text: 'NOIR INTEMPOREL',
        fontFamily: "'Playfair Display', serif",
        fontSize: 52,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1.15,
        color: '#ffffff',
        x: 100,
        y: 800,
        width: 880,
        height: 70,
        rotation: 0,
        opacity: 1,
        zIndex: 4,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-02-copy',
        name: 'Editorial Copy',
        type: 'text',
        text: 'Handcrafted in Grasse. Bottled in hand-blown obsidian crystal.',
        fontFamily: "'Inter', sans-serif",
        fontSize: 16,
        fontWeight: 300,
        textAlign: 'center',
        letterSpacing: 1,
        lineHeight: 1.4,
        color: '#9ca3af',
        x: 140,
        y: 885,
        width: 800,
        height: 35,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 03 — Premium Product Advertisement
  {
    id: 'tpl-03',
    title: 'Premium Product Advertisement',
    category: 'product-advertisement',
    tags: ['Product Advertisement', 'Advertisement', 'Instagram Post'],
    width: 1080,
    height: 1080,
    isTrending: true,
    background: {
      type: 'mesh',
      color: '#0b0f19',
      secondaryColor: '#1e1b4b',
      accentColor: '#4338ca',
      tertiaryColor: '#0f172a',
    },
    elements: [
      {
        id: 'el-03-tag',
        name: 'New Release Tag',
        type: 'shape',
        shapeType: 'pill',
        x: 100,
        y: 110,
        width: 160,
        height: 40,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
        fill: '#4f46e5',
      },
      {
        id: 'el-03-tag-text',
        name: 'Tag Text',
        type: 'text',
        text: 'FLAGSHIP 2027',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 12,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        color: '#ffffff',
        x: 100,
        y: 124,
        width: 160,
        height: 20,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-03-headline',
        name: 'Product Title',
        type: 'text',
        text: 'SPATIAL AUDIO.\nREDEFINED.',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 64,
        fontWeight: 700,
        textAlign: 'left',
        letterSpacing: -1,
        lineHeight: 1.05,
        color: '#ffffff',
        x: 100,
        y: 180,
        width: 600,
        height: 150,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-03-img',
        name: 'Device Product Visual',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1000&q=80',
        x: 200,
        y: 360,
        width: 680,
        height: 480,
        rotation: 0,
        opacity: 1,
        zIndex: 4,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 24,
        filters: { brightness: 100, contrast: 110, saturation: 100, blur: 0, grayscale: 0, duotoneEnabled: false },
        shadow: { enabled: true, color: 'rgba(0,0,0,0.5)', blur: 25, offsetX: 0, offsetY: 12 },
      },
      {
        id: 'el-03-btn',
        name: 'Order Button',
        type: 'shape',
        shapeType: 'pill',
        x: 100,
        y: 890,
        width: 240,
        height: 60,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        locked: false,
        hidden: false,
        fill: '#ffffff',
      },
      {
        id: 'el-03-btn-text',
        name: 'Order Text',
        type: 'text',
        text: 'PRE-ORDER NOW',
        fontFamily: "'Inter', sans-serif",
        fontSize: 15,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 1.5,
        lineHeight: 1,
        color: '#090a0f',
        x: 100,
        y: 912,
        width: 240,
        height: 25,
        rotation: 0,
        opacity: 1,
        zIndex: 6,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 04 — Modern Fashion Poster
  {
    id: 'tpl-04',
    title: 'Modern Fashion Poster',
    category: 'fashion',
    tags: ['Fashion', 'Poster', 'Editorial'],
    width: 1200,
    height: 1600,
    isTrending: true,
    background: {
      type: 'solid',
      color: '#f4f3ef',
    },
    elements: [
      {
        id: 'el-04-bg-title',
        name: 'Big Editorial Background Typography',
        type: 'text',
        text: 'VOGUE',
        fontFamily: "'Playfair Display', serif",
        fontSize: 240,
        fontWeight: 900,
        textAlign: 'center',
        letterSpacing: 10,
        lineHeight: 0.9,
        color: '#e5e3dc',
        x: 0,
        y: 60,
        width: 1200,
        height: 260,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-04-img',
        name: 'Model Shot',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=80',
        x: 200,
        y: 220,
        width: 800,
        height: 1050,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 0,
        filters: { brightness: 100, contrast: 105, saturation: 110, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-04-title',
        name: 'Issue Title',
        type: 'text',
        text: 'THE ESSENCE OF STYLE',
        fontFamily: "'Bebas Neue', sans-serif",
        fontSize: 72,
        fontWeight: 400,
        textAlign: 'left',
        letterSpacing: 4,
        lineHeight: 1,
        color: '#121214',
        x: 100,
        y: 1330,
        width: 700,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-04-subtitle',
        name: 'Issue Subtitle',
        type: 'text',
        text: 'A curated dialogue between minimalism and dramatic avant-garde silhouettes.',
        fontFamily: "'Inter', sans-serif",
        fontSize: 18,
        fontWeight: 400,
        textAlign: 'left',
        letterSpacing: 0.5,
        lineHeight: 1.4,
        color: '#4b5563',
        x: 100,
        y: 1420,
        width: 700,
        height: 60,
        rotation: 0,
        opacity: 1,
        zIndex: 4,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 05 — Streetwear Campaign
  {
    id: 'tpl-05',
    title: 'Streetwear Campaign',
    category: 'fashion',
    tags: ['Fashion', 'Poster', 'Streetwear'],
    width: 1080,
    height: 1920,
    background: {
      type: 'solid',
      color: '#0d0d11',
    },
    elements: [
      {
        id: 'el-05-img',
        name: 'Streetwear Model in Neon',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&w=1000&q=80',
        x: 60,
        y: 300,
        width: 960,
        height: 1100,
        rotation: 0,
        opacity: 0.95,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 20,
        filters: { brightness: 110, contrast: 120, saturation: 110, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-05-headline',
        name: 'Headline',
        type: 'text',
        text: 'UNDERGROUND\nSYNDICATE',
        fontFamily: "'Bebas Neue', sans-serif",
        fontSize: 110,
        fontWeight: 400,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 0.95,
        color: '#ccff00',
        x: 50,
        y: 120,
        width: 980,
        height: 220,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-05-badge',
        name: 'Drop Date Pill',
        type: 'shape',
        shapeType: 'pill',
        x: 340,
        y: 1470,
        width: 400,
        height: 64,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
        fill: '#ccff00',
      },
      {
        id: 'el-05-badge-text',
        name: 'Drop Date Text',
        type: 'text',
        text: 'LIMITED DROP • 10.24.27',
        fontFamily: "'Inter', sans-serif",
        fontSize: 18,
        fontWeight: 800,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        color: '#0d0d11',
        x: 340,
        y: 1492,
        width: 400,
        height: 30,
        rotation: 0,
        opacity: 1,
        zIndex: 4,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 06 — Luxury Watch Advertisement
  {
    id: 'tpl-06',
    title: 'Luxury Watch Advertisement',
    category: 'luxury-brand',
    tags: ['Luxury Brand', 'Watch', 'Advertisement'],
    width: 1200,
    height: 1600,
    background: {
      type: 'dark-luxury',
      color: '#090a0d',
      secondaryColor: 'rgba(197, 160, 89, 0.2)',
    },
    elements: [
      {
        id: 'el-06-img',
        name: 'Chronograph Watch',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80',
        x: 150,
        y: 280,
        width: 900,
        height: 800,
        rotation: 0,
        opacity: 0.95,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 20,
        filters: { brightness: 105, contrast: 115, saturation: 90, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-06-kicker',
        name: 'Heritage Kicker',
        type: 'text',
        text: 'GENÈVE 1884 • HAUTE HORLOGERIE',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 16,
        fontWeight: 600,
        textAlign: 'center',
        letterSpacing: 6,
        lineHeight: 1.2,
        color: '#c5a059',
        x: 100,
        y: 120,
        width: 1000,
        height: 30,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-06-headline',
        name: 'Main Title',
        type: 'text',
        text: 'MASTERY OVER TIME',
        fontFamily: "'Cinzel', serif",
        fontSize: 64,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 6,
        lineHeight: 1.1,
        color: '#ffffff',
        x: 100,
        y: 160,
        width: 1000,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-06-desc',
        name: 'Technical Description',
        type: 'text',
        text: 'Hand-finished titanium casing with perpetual tourbillon movement.',
        fontFamily: "'Inter', sans-serif",
        fontSize: 18,
        fontWeight: 300,
        textAlign: 'center',
        letterSpacing: 1.5,
        lineHeight: 1.5,
        color: '#a1a1aa',
        x: 200,
        y: 1160,
        width: 800,
        height: 60,
        rotation: 0,
        opacity: 1,
        zIndex: 4,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 07 — Perfume Advertisement
  {
    id: 'tpl-07',
    title: 'Perfume Advertisement',
    category: 'luxury-brand',
    tags: ['Luxury Brand', 'Advertisement', 'Poster'],
    width: 1080,
    height: 1080,
    background: {
      type: 'solid',
      color: '#121015',
    },
    elements: [
      {
        id: 'el-07-img',
        name: 'Fragrance Bottle',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1000&q=80',
        x: 240,
        y: 140,
        width: 600,
        height: 620,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 16,
        filters: { brightness: 105, contrast: 110, saturation: 95, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-07-title',
        name: 'Fragrance Name',
        type: 'text',
        text: 'SOLITUDE SACRÉE',
        fontFamily: "'Playfair Display', serif",
        fontSize: 48,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1.2,
        color: '#f5d061',
        x: 100,
        y: 810,
        width: 880,
        height: 60,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-07-notes',
        name: 'Scent Notes',
        type: 'text',
        text: 'Black Amber • Wild Iris • Smoked Oud',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 16,
        fontWeight: 400,
        textAlign: 'center',
        letterSpacing: 3,
        lineHeight: 1.4,
        color: '#d1d5db',
        x: 100,
        y: 880,
        width: 880,
        height: 30,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 08 — Sports Announcement
  {
    id: 'tpl-08',
    title: 'Sports Announcement',
    category: 'sports',
    tags: ['Sports', 'Social Media', 'Announcement'],
    width: 1080,
    height: 1080,
    isTrending: true,
    background: {
      type: 'solid',
      color: '#0b0c10',
    },
    elements: [
      {
        id: 'el-08-img',
        name: 'Athlete in Action',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
        x: 80,
        y: 200,
        width: 920,
        height: 600,
        rotation: 0,
        opacity: 0.88,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 16,
        filters: { brightness: 100, contrast: 125, saturation: 110, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-08-title',
        name: 'Match Title',
        type: 'text',
        text: 'CHAMPIONSHIP FINALS',
        fontFamily: "'Oswald', sans-serif",
        fontSize: 68,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        color: '#ff4655',
        x: 50,
        y: 80,
        width: 980,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-08-date',
        name: 'Date Banner',
        type: 'text',
        text: 'SATURDAY • 8:00 PM EST • LIVE ON STREAM',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 18,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1.2,
        color: '#ffffff',
        x: 50,
        y: 860,
        width: 980,
        height: 40,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 09 — Football Match Poster
  {
    id: 'tpl-09',
    title: 'Football Match Poster',
    category: 'sports',
    tags: ['Sports', 'Poster', 'Match Day'],
    width: 1200,
    height: 1600,
    background: {
      type: 'solid',
      color: '#0a0d18',
    },
    elements: [
      {
        id: 'el-09-img',
        name: 'Stadium Match Lights',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80',
        x: 80,
        y: 280,
        width: 1040,
        height: 750,
        rotation: 0,
        opacity: 0.9,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 24,
        filters: { brightness: 105, contrast: 120, saturation: 115, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-09-headline',
        name: 'Match Day Headline',
        type: 'text',
        text: 'DERBY CLASH',
        fontFamily: "'Oswald', sans-serif",
        fontSize: 96,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1,
        color: '#ffffff',
        x: 100,
        y: 110,
        width: 1000,
        height: 110,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-09-teams',
        name: 'Team Matchup',
        type: 'text',
        text: 'TITANS FC  vs  APEX UNITED',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 32,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1.2,
        color: '#38bdf8',
        x: 100,
        y: 1100,
        width: 1000,
        height: 50,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 10 — Basketball Event Poster
  {
    id: 'tpl-10',
    title: 'Basketball Event Poster',
    category: 'sports',
    tags: ['Sports', 'Poster', 'Basketball'],
    width: 1200,
    height: 1600,
    background: {
      type: 'solid',
      color: '#111015',
    },
    elements: [
      {
        id: 'el-10-img',
        name: 'Court Slam Dunk',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80',
        x: 100,
        y: 280,
        width: 1000,
        height: 800,
        rotation: 0,
        opacity: 0.9,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 20,
        filters: { brightness: 105, contrast: 115, saturation: 110, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-10-title',
        name: 'Tournament Header',
        type: 'text',
        text: 'SUMMER SLAM ALL-STARS',
        fontFamily: "'Bebas Neue', sans-serif",
        fontSize: 88,
        fontWeight: 400,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1,
        color: '#ff7700',
        x: 80,
        y: 120,
        width: 1040,
        height: 100,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 11 — Fitness Campaign
  {
    id: 'tpl-11',
    title: 'Fitness Campaign',
    category: 'sports',
    tags: ['Sports', 'Fitness', 'Social Media'],
    width: 1080,
    height: 1080,
    background: {
      type: 'solid',
      color: '#0c0d12',
    },
    elements: [
      {
        id: 'el-11-img',
        name: 'Gym Workout',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
        x: 80,
        y: 160,
        width: 920,
        height: 600,
        rotation: 0,
        opacity: 0.9,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 16,
        filters: { brightness: 100, contrast: 120, saturation: 90, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-11-headline',
        name: 'Motto',
        type: 'text',
        text: 'CONQUER YOUR LIMITS',
        fontFamily: "'Oswald', sans-serif",
        fontSize: 60,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        color: '#ccff00',
        x: 50,
        y: 800,
        width: 980,
        height: 70,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 12 — Music Festival Poster
  {
    id: 'tpl-12',
    title: 'Music Festival Poster',
    category: 'music',
    tags: ['Music', 'Poster', 'Festival'],
    width: 1200,
    height: 1600,
    isTrending: true,
    background: {
      type: 'neon',
      color: '#070710',
    },
    elements: [
      {
        id: 'el-12-img',
        name: 'Stage Light Beams',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80',
        x: 100,
        y: 260,
        width: 1000,
        height: 700,
        rotation: 0,
        opacity: 0.9,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 24,
        filters: { brightness: 110, contrast: 115, saturation: 120, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-12-title',
        name: 'Festival Name',
        type: 'text',
        text: 'SONIC HORIZON',
        fontFamily: "'Syne', sans-serif",
        fontSize: 84,
        fontWeight: 800,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        color: '#ffffff',
        x: 80,
        y: 110,
        width: 1040,
        height: 100,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-12-lineup',
        name: 'Lineup',
        type: 'text',
        text: 'KAYTRANADA • ODESZA • BONOBO • TYCHO • LANE 8',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 24,
        fontWeight: 600,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1.4,
        color: '#38bdf8',
        x: 100,
        y: 1050,
        width: 1000,
        height: 60,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 13 — Concert Announcement
  {
    id: 'tpl-13',
    title: 'Concert Announcement',
    category: 'music',
    tags: ['Music', 'Concert', 'Instagram Story'],
    width: 1080,
    height: 1920,
    background: {
      type: 'solid',
      color: '#0f0e17',
    },
    elements: [
      {
        id: 'el-13-img',
        name: 'Live Performer',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80',
        x: 80,
        y: 350,
        width: 920,
        height: 980,
        rotation: 0,
        opacity: 0.95,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 20,
        filters: { brightness: 105, contrast: 115, saturation: 110, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-13-headline',
        name: 'Tour Title',
        type: 'text',
        text: 'WORLD TOUR 2027',
        fontFamily: "'Bebas Neue', sans-serif",
        fontSize: 90,
        fontWeight: 400,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1,
        color: '#ff0055',
        x: 50,
        y: 150,
        width: 980,
        height: 100,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 14 — DJ Event Poster
  {
    id: 'tpl-14',
    title: 'DJ Event Poster',
    category: 'music',
    tags: ['Music', 'Nightclub', 'Poster'],
    width: 1200,
    height: 1600,
    background: {
      type: 'neon',
      color: '#090a10',
    },
    elements: [
      {
        id: 'el-14-img',
        name: 'DJ Console',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80',
        x: 100,
        y: 260,
        width: 1000,
        height: 750,
        rotation: 0,
        opacity: 0.92,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 20,
        filters: { brightness: 105, contrast: 120, saturation: 120, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-14-title',
        name: 'DJ Name',
        type: 'text',
        text: 'NIGHT PULSE SESSIONS',
        fontFamily: "'Syne', sans-serif",
        fontSize: 70,
        fontWeight: 800,
        textAlign: 'center',
        letterSpacing: 3,
        lineHeight: 1,
        color: '#00f2fe',
        x: 80,
        y: 120,
        width: 1040,
        height: 90,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 15 — Movie Poster
  {
    id: 'tpl-15',
    title: 'Movie Poster',
    category: 'poster',
    tags: ['Poster', 'Film', 'Cinematic'],
    width: 1200,
    height: 1600,
    isPremium: true,
    background: {
      type: 'solid',
      color: '#08080a',
    },
    elements: [
      {
        id: 'el-15-img',
        name: 'Cinematic Visual',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
        x: 80,
        y: 180,
        width: 1040,
        height: 920,
        rotation: 0,
        opacity: 0.9,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 16,
        filters: { brightness: 95, contrast: 120, saturation: 80, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-15-title',
        name: 'Movie Title',
        type: 'text',
        text: 'INTERSTELLAR DUSK',
        fontFamily: "'Cinzel', serif",
        fontSize: 72,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 8,
        lineHeight: 1,
        color: '#ffffff',
        x: 50,
        y: 1180,
        width: 1100,
        height: 85,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-15-date',
        name: 'Release Date',
        type: 'text',
        text: 'IN THEATERS AND IMAX • NOVEMBER 2027',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 16,
        fontWeight: 600,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1.2,
        color: '#c5a059',
        x: 100,
        y: 1290,
        width: 1000,
        height: 30,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 16 — Cinematic Film Announcement
  {
    id: 'tpl-16',
    title: 'Cinematic Film Announcement',
    category: 'poster',
    tags: ['Poster', 'Cinematic', 'Social Media'],
    width: 1080,
    height: 1080,
    background: {
      type: 'dark-luxury',
      color: '#0a0a0d',
    },
    elements: [
      {
        id: 'el-16-title',
        name: 'Main Title',
        type: 'text',
        text: 'OFFICIAL SELECTION',
        fontFamily: "'Cinzel', serif",
        fontSize: 42,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 6,
        lineHeight: 1.2,
        color: '#d4af37',
        x: 100,
        y: 140,
        width: 880,
        height: 60,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-16-film',
        name: 'Film Name',
        type: 'text',
        text: 'CHRONICLES OF ECHO',
        fontFamily: "'Playfair Display', serif",
        fontSize: 60,
        fontWeight: 900,
        textAlign: 'center',
        letterSpacing: 3,
        lineHeight: 1.1,
        color: '#ffffff',
        x: 80,
        y: 440,
        width: 920,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 17 — Technology Product Launch
  {
    id: 'tpl-17',
    title: 'Technology Product Launch',
    category: 'technology',
    tags: ['Technology', 'Product Launch', 'Presentation'],
    width: 1920,
    height: 1080,
    isTrending: true,
    background: {
      type: 'mesh',
      color: '#07080e',
      secondaryColor: '#1e1b4b',
      accentColor: '#0ea5e9',
      tertiaryColor: '#4f46e5',
    },
    elements: [
      {
        id: 'el-17-badge',
        name: 'Pill Badge',
        type: 'shape',
        shapeType: 'pill',
        x: 120,
        y: 180,
        width: 180,
        height: 44,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
        fill: '#0284c7',
      },
      {
        id: 'el-17-badge-txt',
        name: 'Badge Text',
        type: 'text',
        text: 'KEYNOTE 2027',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 14,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        color: '#ffffff',
        x: 120,
        y: 195,
        width: 180,
        height: 25,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-17-title',
        name: 'Keynote Title',
        type: 'text',
        text: 'SYNAPSE AI ENGINE 4.0',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 72,
        fontWeight: 700,
        textAlign: 'left',
        letterSpacing: -1,
        lineHeight: 1.05,
        color: '#ffffff',
        x: 120,
        y: 260,
        width: 900,
        height: 160,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-17-img',
        name: 'AI Neural Visual',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
        x: 1040,
        y: 160,
        width: 760,
        height: 760,
        rotation: 0,
        opacity: 0.95,
        zIndex: 4,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 32,
        filters: { brightness: 105, contrast: 115, saturation: 110, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
    ],
  },

  // 18 — AI Startup Advertisement
  {
    id: 'tpl-18',
    title: 'AI Startup Advertisement',
    category: 'technology',
    tags: ['Technology', 'Advertisement', 'Social Media'],
    width: 1080,
    height: 1080,
    background: {
      type: 'neon',
      color: '#080a12',
    },
    elements: [
      {
        id: 'el-18-title',
        name: 'Headline',
        type: 'text',
        text: 'INTELLIGENCE AT THE SPEED OF THOUGHT',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 54,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: -0.5,
        lineHeight: 1.15,
        color: '#ffffff',
        x: 80,
        y: 120,
        width: 920,
        height: 130,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-18-img',
        name: 'Neural AI Core',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
        x: 160,
        y: 300,
        width: 760,
        height: 520,
        rotation: 0,
        opacity: 0.95,
        zIndex: 2,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 24,
        filters: { brightness: 105, contrast: 110, saturation: 100, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
    ],
  },

  // 19 — Smartphone Advertisement
  {
    id: 'tpl-19',
    title: 'Smartphone Advertisement',
    category: 'technology',
    tags: ['Technology', 'Product Advertisement', 'Smartphone'],
    width: 1080,
    height: 1920,
    background: {
      type: 'solid',
      color: '#07080a',
    },
    elements: [
      {
        id: 'el-19-img',
        name: 'Smartphone Device',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1000&q=80',
        x: 90,
        y: 400,
        width: 900,
        height: 1050,
        rotation: 0,
        opacity: 0.95,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 24,
        filters: { brightness: 105, contrast: 115, saturation: 100, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-19-title',
        name: 'Device Headline',
        type: 'text',
        text: 'NEXUS PRO ZERO',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 76,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        color: '#38bdf8',
        x: 50,
        y: 180,
        width: 980,
        height: 90,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 20 — Gaming Tournament Poster
  {
    id: 'tpl-20',
    title: 'Gaming Tournament Poster',
    category: 'sports',
    tags: ['Sports', 'Gaming', 'Poster'],
    width: 1200,
    height: 1600,
    background: {
      type: 'neon',
      color: '#080811',
    },
    elements: [
      {
        id: 'el-20-title',
        name: 'Tournament Title',
        type: 'text',
        text: 'CYBER ARENA INVITATIONAL',
        fontFamily: "'Syne', sans-serif",
        fontSize: 78,
        fontWeight: 800,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1.05,
        color: '#ff0055',
        x: 80,
        y: 140,
        width: 1040,
        height: 170,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-20-pool',
        name: 'Prize Pool',
        type: 'text',
        text: '$500,000 PRIZE POOL • GRAND FINALS',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 28,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 3,
        lineHeight: 1,
        color: '#00f2fe',
        x: 80,
        y: 1200,
        width: 1040,
        height: 40,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 21 — Restaurant Promotion
  {
    id: 'tpl-21',
    title: 'Restaurant Promotion',
    category: 'restaurant',
    tags: ['Restaurant', 'Food', 'Social Media'],
    width: 1080,
    height: 1080,
    isTrending: true,
    background: {
      type: 'dark-luxury',
      color: '#100f13',
    },
    elements: [
      {
        id: 'el-21-img',
        name: 'Gourmet Dish',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
        x: 90,
        y: 120,
        width: 900,
        height: 620,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 20,
        filters: { brightness: 100, contrast: 110, saturation: 110, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-21-title',
        name: 'Promotion Headline',
        type: 'text',
        text: 'AN EPICUREAN JOURNEY',
        fontFamily: "'Playfair Display', serif",
        fontSize: 50,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1.15,
        color: '#f5d061',
        x: 100,
        y: 780,
        width: 880,
        height: 60,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-21-sub',
        name: 'Tasting Menu Subtitle',
        type: 'text',
        text: 'Seven-course autumn tasting menu curated by Chef Laurent.',
        fontFamily: "'Inter', sans-serif",
        fontSize: 18,
        fontWeight: 300,
        textAlign: 'center',
        letterSpacing: 1,
        lineHeight: 1.4,
        color: '#9ca3af',
        x: 120,
        y: 860,
        width: 840,
        height: 50,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 22 — Food Advertisement
  {
    id: 'tpl-22',
    title: 'Food Advertisement',
    category: 'restaurant',
    tags: ['Restaurant', 'Food', 'Advertisement'],
    width: 1080,
    height: 1080,
    background: {
      type: 'solid',
      color: '#141216',
    },
    elements: [
      {
        id: 'el-22-title',
        name: 'Headline',
        type: 'text',
        text: 'FRESH ARTISAN FLAVORS',
        fontFamily: "'Oswald', sans-serif",
        fontSize: 62,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        color: '#ff9800',
        x: 50,
        y: 100,
        width: 980,
        height: 75,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 23 — Coffee Shop Promotion
  {
    id: 'tpl-23',
    title: 'Coffee Shop Promotion',
    category: 'restaurant',
    tags: ['Restaurant', 'Coffee', 'Social Media'],
    width: 1080,
    height: 1080,
    background: {
      type: 'solid',
      color: '#181412',
    },
    elements: [
      {
        id: 'el-23-img',
        name: 'Artisan Latte',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
        x: 90,
        y: 120,
        width: 900,
        height: 600,
        rotation: 0,
        opacity: 0.95,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 20,
        filters: { brightness: 100, contrast: 110, saturation: 100, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-23-title',
        name: 'Cafe Title',
        type: 'text',
        text: 'ROASTED TO PERFECTION',
        fontFamily: "'Playfair Display', serif",
        fontSize: 48,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1.2,
        color: '#d4a373',
        x: 100,
        y: 780,
        width: 880,
        height: 60,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 24 — Travel Campaign
  {
    id: 'tpl-24',
    title: 'Travel Campaign',
    category: 'travel',
    tags: ['Travel', 'Campaign', 'Poster'],
    width: 1200,
    height: 1600,
    isTrending: true,
    background: {
      type: 'solid',
      color: '#090e17',
    },
    elements: [
      {
        id: 'el-24-img',
        name: 'Overwater Villa',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        x: 80,
        y: 200,
        width: 1040,
        height: 900,
        rotation: 0,
        opacity: 0.95,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 24,
        filters: { brightness: 105, contrast: 110, saturation: 115, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-24-title',
        name: 'Travel Destination',
        type: 'text',
        text: 'DISCOVER PARADISE',
        fontFamily: "'Playfair Display', serif",
        fontSize: 76,
        fontWeight: 900,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1.1,
        color: '#ffffff',
        x: 80,
        y: 1180,
        width: 1040,
        height: 90,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 25 — Luxury Hotel Advertisement
  {
    id: 'tpl-25',
    title: 'Luxury Hotel Advertisement',
    category: 'travel',
    tags: ['Travel', 'Hotel', 'Luxury Brand'],
    width: 1080,
    height: 1080,
    background: {
      type: 'dark-luxury',
      color: '#0d0d12',
    },
    elements: [
      {
        id: 'el-25-title',
        name: 'Hotel Name',
        type: 'text',
        text: 'THE OBSIDIAN SANCTUARY',
        fontFamily: "'Cinzel', serif",
        fontSize: 50,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 6,
        lineHeight: 1.2,
        color: '#c5a059',
        x: 80,
        y: 180,
        width: 920,
        height: 70,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 26 — Summer Travel Poster
  {
    id: 'tpl-26',
    title: 'Summer Travel Poster',
    category: 'travel',
    tags: ['Travel', 'Summer', 'Poster'],
    width: 1200,
    height: 1600,
    background: {
      type: 'sunset',
      color: '#1a0b2e',
      secondaryColor: '#801850',
      accentColor: '#ff6b4a',
    },
    elements: [
      {
        id: 'el-26-title',
        name: 'Summer Title',
        type: 'text',
        text: 'ENDLESS SUMMER',
        fontFamily: "'Bebas Neue', sans-serif",
        fontSize: 100,
        fontWeight: 400,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1,
        color: '#ffffff',
        x: 80,
        y: 180,
        width: 1040,
        height: 110,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 27 — Business Conference
  {
    id: 'tpl-27',
    title: 'Business Conference',
    category: 'business',
    tags: ['Business', 'Event', 'Conference'],
    width: 1920,
    height: 1080,
    isTrending: true,
    background: {
      type: 'solid',
      color: '#0a0d16',
    },
    elements: [
      {
        id: 'el-27-title',
        name: 'Conference Title',
        type: 'text',
        text: 'GLOBAL SUMMIT 2027',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 80,
        fontWeight: 700,
        textAlign: 'left',
        letterSpacing: -1,
        lineHeight: 1.05,
        color: '#ffffff',
        x: 120,
        y: 220,
        width: 900,
        height: 180,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-27-img',
        name: 'Keynote Speaker',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80',
        x: 1080,
        y: 180,
        width: 720,
        height: 720,
        rotation: 0,
        opacity: 0.95,
        zIndex: 2,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 24,
        filters: { brightness: 100, contrast: 110, saturation: 95, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
    ],
  },

  // 28 — Startup Pitch Presentation
  {
    id: 'tpl-28',
    title: 'Startup Pitch Presentation',
    category: 'presentation',
    tags: ['Presentation', 'Business', 'Startup'],
    width: 1920,
    height: 1080,
    background: {
      type: 'mesh',
      color: '#080a12',
      secondaryColor: '#1e1b4b',
      accentColor: '#3b82f6',
      tertiaryColor: '#6366f1',
    },
    elements: [
      {
        id: 'el-28-title',
        name: 'Deck Title',
        type: 'text',
        text: 'DISRUPTING DIGITAL COMMERCE',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 76,
        fontWeight: 700,
        textAlign: 'left',
        letterSpacing: -1,
        lineHeight: 1.1,
        color: '#ffffff',
        x: 120,
        y: 300,
        width: 1100,
        height: 170,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 29 — Corporate Announcement
  {
    id: 'tpl-29',
    title: 'Corporate Announcement',
    category: 'business',
    tags: ['Business', 'Corporate', 'Announcement'],
    width: 1200,
    height: 630,
    background: {
      type: 'solid',
      color: '#0e121e',
    },
    elements: [
      {
        id: 'el-29-title',
        name: 'Corporate Title',
        type: 'text',
        text: 'STRATEGIC PARTNERSHIP ANNOUNCEMENT',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 48,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 1,
        lineHeight: 1.2,
        color: '#38bdf8',
        x: 80,
        y: 180,
        width: 1040,
        height: 120,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 30 — Business Instagram Post
  {
    id: 'tpl-30',
    title: 'Business Instagram Post',
    category: 'instagram-post',
    tags: ['Instagram Post', 'Business', 'Marketing'],
    width: 1080,
    height: 1080,
    background: {
      type: 'geometric',
      color: '#0c0e17',
    },
    elements: [
      {
        id: 'el-30-title',
        name: 'Insight Heading',
        type: 'text',
        text: '3 PILLARS OF RAPID SCALE',
        fontFamily: "'Plus Jakarta Sans', sans-serif",
        fontSize: 54,
        fontWeight: 800,
        textAlign: 'center',
        letterSpacing: -0.5,
        lineHeight: 1.15,
        color: '#ffffff',
        x: 80,
        y: 200,
        width: 920,
        height: 130,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 31 — Real Estate Advertisement
  {
    id: 'tpl-31',
    title: 'Real Estate Advertisement',
    category: 'advertisement',
    tags: ['Advertisement', 'Real Estate', 'Luxury Brand'],
    width: 1080,
    height: 1080,
    background: {
      type: 'solid',
      color: '#0e0f14',
    },
    elements: [
      {
        id: 'el-31-img',
        name: 'Architectural Villa',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
        x: 80,
        y: 120,
        width: 920,
        height: 600,
        rotation: 0,
        opacity: 0.95,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 20,
        filters: { brightness: 100, contrast: 110, saturation: 100, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-31-title',
        name: 'Penthouse Title',
        type: 'text',
        text: 'THE SKYLINE RESIDENCES',
        fontFamily: "'Cinzel', serif",
        fontSize: 48,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1.2,
        color: '#ffffff',
        x: 80,
        y: 770,
        width: 920,
        height: 60,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 32 — Education Campaign
  {
    id: 'tpl-32',
    title: 'Education Campaign',
    category: 'education',
    tags: ['Education', 'Online Course', 'Poster'],
    width: 1200,
    height: 1600,
    background: {
      type: 'solid',
      color: '#090b14',
    },
    elements: [
      {
        id: 'el-32-title',
        name: 'Academy Title',
        type: 'text',
        text: 'ADVANCED AI & MACHINE LEARNING',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 72,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: -1,
        lineHeight: 1.1,
        color: '#60a5fa',
        x: 80,
        y: 180,
        width: 1040,
        height: 160,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 33 — Online Course Advertisement
  {
    id: 'tpl-33',
    title: 'Online Course Advertisement',
    category: 'education',
    tags: ['Education', 'Advertisement', 'Social Media'],
    width: 1080,
    height: 1080,
    background: {
      type: 'mesh',
      color: '#080a14',
      secondaryColor: '#1d4ed8',
      accentColor: '#7c3aed',
      tertiaryColor: '#0ea5e9',
    },
    elements: [
      {
        id: 'el-33-title',
        name: 'Course Title',
        type: 'text',
        text: 'MASTER PRODUCT DESIGN',
        fontFamily: "'Outfit', sans-serif",
        fontSize: 64,
        fontWeight: 800,
        textAlign: 'center',
        letterSpacing: -1,
        lineHeight: 1.1,
        color: '#ffffff',
        x: 80,
        y: 200,
        width: 920,
        height: 140,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 34 — Graduation Announcement
  {
    id: 'tpl-34',
    title: 'Graduation Announcement',
    category: 'education',
    tags: ['Education', 'Announcement', 'Invitation'],
    width: 1200,
    height: 1600,
    background: {
      type: 'dark-luxury',
      color: '#0a0a0f',
    },
    elements: [
      {
        id: 'el-34-title',
        name: 'Honors Header',
        type: 'text',
        text: 'COMMENCEMENT EXERCISES',
        fontFamily: "'Cinzel', serif",
        fontSize: 60,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 6,
        lineHeight: 1.2,
        color: '#d4af37',
        x: 80,
        y: 200,
        width: 1040,
        height: 140,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 35 — Certificate Design
  {
    id: 'tpl-35',
    title: 'Certificate Design',
    category: 'certificate',
    tags: ['Certificate', 'Education', 'Print'],
    width: 1754,
    height: 1240,
    background: {
      type: 'solid',
      color: '#090a10',
    },
    elements: [
      {
        id: 'el-35-border',
        name: 'Gold Filigree Border',
        type: 'shape',
        shapeType: 'rectangle',
        x: 50,
        y: 50,
        width: 1654,
        height: 1140,
        rotation: 0,
        opacity: 0.8,
        zIndex: 1,
        locked: false,
        hidden: false,
        fill: 'transparent',
        strokeColor: '#c5a059',
        strokeWidth: 4,
      },
      {
        id: 'el-35-title',
        name: 'Certificate Header',
        type: 'text',
        text: 'CERTIFICATE OF EXCELLENCE',
        fontFamily: "'Cinzel', serif",
        fontSize: 64,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 8,
        lineHeight: 1.2,
        color: '#c5a059',
        x: 100,
        y: 180,
        width: 1554,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-35-rec',
        name: 'Recipient Name',
        type: 'text',
        text: 'ALEXANDER VAUGHN',
        fontFamily: "'Playfair Display', serif",
        fontSize: 52,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1.2,
        color: '#ffffff',
        x: 100,
        y: 480,
        width: 1554,
        height: 70,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 36 — Wedding Invitation
  {
    id: 'tpl-36',
    title: 'Wedding Invitation',
    category: 'invitation',
    tags: ['Invitation', 'Wedding', 'Elegant'],
    width: 1200,
    height: 1600,
    isPremium: true,
    background: {
      type: 'solid',
      color: '#0f0e13',
    },
    elements: [
      {
        id: 'el-36-title',
        name: 'Names',
        type: 'text',
        text: 'ELEANOR & THEODORE',
        fontFamily: "'Cinzel', serif",
        fontSize: 64,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 6,
        lineHeight: 1.2,
        color: '#f5d061',
        x: 80,
        y: 280,
        width: 1040,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-36-sub',
        name: 'Ceremony Details',
        type: 'text',
        text: 'Request the honor of your presence at their marriage celebration.',
        fontFamily: "'Cormorant Garamond', serif",
        fontSize: 26,
        fontWeight: 400,
        textAlign: 'center',
        letterSpacing: 1.5,
        lineHeight: 1.5,
        color: '#d1d5db',
        x: 150,
        y: 420,
        width: 900,
        height: 70,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 37 — Birthday Invitation
  {
    id: 'tpl-37',
    title: 'Birthday Invitation',
    category: 'invitation',
    tags: ['Invitation', 'Birthday', 'Social Media'],
    width: 1080,
    height: 1920,
    background: {
      type: 'neon',
      color: '#0d0d16',
    },
    elements: [
      {
        id: 'el-37-title',
        name: 'Birthday Title',
        type: 'text',
        text: 'VIP 30TH CELEBRATION',
        fontFamily: "'Bebas Neue', sans-serif",
        fontSize: 92,
        fontWeight: 400,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1,
        color: '#ff007f',
        x: 50,
        y: 240,
        width: 980,
        height: 100,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 38 — Minimal Quote Poster
  {
    id: 'tpl-38',
    title: 'Minimal Quote Poster',
    category: 'quote',
    tags: ['Quote', 'Minimalist', 'Poster'],
    width: 1200,
    height: 1600,
    background: {
      type: 'solid',
      color: '#08080a',
    },
    elements: [
      {
        id: 'el-38-quote',
        name: 'Quote Text',
        type: 'text',
        text: '“Simplicity is the ultimate sophistication.”',
        fontFamily: "'Playfair Display', serif",
        fontSize: 72,
        fontWeight: 600,
        textAlign: 'center',
        letterSpacing: -0.5,
        lineHeight: 1.25,
        color: '#ffffff',
        x: 100,
        y: 500,
        width: 1000,
        height: 240,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-38-author',
        name: 'Author Attribution',
        type: 'text',
        text: '— LEONARDO DA VINCI',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 20,
        fontWeight: 600,
        textAlign: 'center',
        letterSpacing: 6,
        lineHeight: 1.2,
        color: '#9ca3af',
        x: 100,
        y: 800,
        width: 1000,
        height: 35,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 39 — Motivational Campaign
  {
    id: 'tpl-39',
    title: 'Motivational Campaign',
    category: 'quote',
    tags: ['Quote', 'Motivational', 'Social Media'],
    width: 1080,
    height: 1080,
    background: {
      type: 'solid',
      color: '#0b0c10',
    },
    elements: [
      {
        id: 'el-39-title',
        name: 'Big Text',
        type: 'text',
        text: 'DREAM BOLD.\nBUILD RELENTLESSLY.',
        fontFamily: "'Bebas Neue', sans-serif",
        fontSize: 90,
        fontWeight: 400,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        color: '#ccff00',
        x: 50,
        y: 400,
        width: 980,
        height: 200,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 40 — Magazine Cover
  {
    id: 'tpl-40',
    title: 'Magazine Cover',
    category: 'magazine',
    tags: ['Magazine', 'Fashion', 'Editorial'],
    width: 1200,
    height: 1600,
    isPremium: true,
    background: {
      type: 'solid',
      color: '#08080a',
    },
    elements: [
      {
        id: 'el-40-img',
        name: 'Cover Star',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=80',
        x: 100,
        y: 180,
        width: 1000,
        height: 1300,
        rotation: 0,
        opacity: 0.95,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 0,
        filters: { brightness: 105, contrast: 110, saturation: 90, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-40-masthead',
        name: 'Masthead',
        type: 'text',
        text: 'AVANT-GARDE',
        fontFamily: "'Playfair Display', serif",
        fontSize: 130,
        fontWeight: 900,
        textAlign: 'center',
        letterSpacing: 6,
        lineHeight: 0.95,
        color: '#ffffff',
        x: 50,
        y: 80,
        width: 1100,
        height: 140,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 41 — Album Cover
  {
    id: 'tpl-41',
    title: 'Album Cover',
    category: 'album-cover',
    tags: ['Album Cover', 'Music', 'Vinyl'],
    width: 1400,
    height: 1400,
    background: {
      type: 'neon',
      color: '#05060b',
    },
    elements: [
      {
        id: 'el-41-title',
        name: 'Album Title',
        type: 'text',
        text: 'SYNTHETIC DREAMS',
        fontFamily: "'Syne', sans-serif",
        fontSize: 90,
        fontWeight: 800,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1,
        color: '#00ffcc',
        x: 100,
        y: 600,
        width: 1200,
        height: 110,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 42 — YouTube Thumbnail
  {
    id: 'tpl-42',
    title: 'YouTube Thumbnail',
    category: 'youtube-thumbnail',
    tags: ['YouTube Thumbnail', 'Video', 'High CTR'],
    width: 1280,
    height: 720,
    isTrending: true,
    background: {
      type: 'solid',
      color: '#0a0a10',
    },
    elements: [
      {
        id: 'el-42-pill',
        name: 'Warning Tag',
        type: 'shape',
        shapeType: 'pill',
        x: 80,
        y: 100,
        width: 220,
        height: 52,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
        fill: '#e50914',
      },
      {
        id: 'el-42-pill-text',
        name: 'Tag Text',
        type: 'text',
        text: 'EXPOSED 2027',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 16,
        fontWeight: 800,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        color: '#ffffff',
        x: 80,
        y: 117,
        width: 220,
        height: 25,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-42-title',
        name: 'Clickbait Hook',
        type: 'text',
        text: 'THE AI REVOLUTION\nIS ALREADY HERE.',
        fontFamily: "'Bebas Neue', sans-serif",
        fontSize: 82,
        fontWeight: 400,
        textAlign: 'left',
        letterSpacing: 2,
        lineHeight: 0.95,
        color: '#ffffff',
        x: 80,
        y: 180,
        width: 750,
        height: 180,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 43 — YouTube Channel Banner
  {
    id: 'tpl-43',
    title: 'YouTube Channel Banner',
    category: 'youtube-banner',
    tags: ['YouTube Banner', 'Video', 'Header'],
    width: 2560,
    height: 1440,
    background: {
      type: 'mesh',
      color: '#07080f',
      secondaryColor: '#3b82f6',
      accentColor: '#8b5cf6',
      tertiaryColor: '#ec4899',
    },
    elements: [
      {
        id: 'el-43-channel',
        name: 'Channel Name',
        type: 'text',
        text: 'ANTIGRAVITY CREATIVE',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 100,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1,
        color: '#ffffff',
        x: 200,
        y: 600,
        width: 2160,
        height: 120,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 44 — Instagram Story Campaign
  {
    id: 'tpl-44',
    title: 'Instagram Story Campaign',
    category: 'instagram-story',
    tags: ['Instagram Story', 'Social Media', 'Promotion'],
    width: 1080,
    height: 1920,
    background: {
      type: 'aurora',
      color: '#06070c',
      secondaryColor: 'rgba(120, 119, 198, 0.5)',
      accentColor: 'rgba(56, 189, 248, 0.4)',
      tertiaryColor: 'rgba(168, 85, 247, 0.4)',
    },
    elements: [
      {
        id: 'el-44-title',
        name: 'Story Headline',
        type: 'text',
        text: 'EXCLUSIVE VIP DROP',
        fontFamily: "'Plus Jakarta Sans', sans-serif",
        fontSize: 68,
        fontWeight: 800,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1.1,
        color: '#ffffff',
        x: 80,
        y: 300,
        width: 920,
        height: 160,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 45 — Product Launch Story
  {
    id: 'tpl-45',
    title: 'Product Launch Story',
    category: 'instagram-story',
    tags: ['Instagram Story', 'Product Advertisement', 'Launch'],
    width: 1080,
    height: 1920,
    background: {
      type: 'solid',
      color: '#090a10',
    },
    elements: [
      {
        id: 'el-45-title',
        name: 'Launch Text',
        type: 'text',
        text: 'MEET THE FUTURE',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 76,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        color: '#38bdf8',
        x: 50,
        y: 280,
        width: 980,
        height: 90,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 46 — Portfolio Cover
  {
    id: 'tpl-46',
    title: 'Portfolio Cover',
    category: 'portfolio',
    tags: ['Portfolio', 'Design', 'Minimalist'],
    width: 1920,
    height: 1080,
    background: {
      type: 'solid',
      color: '#0c0c0e',
    },
    elements: [
      {
        id: 'el-46-name',
        name: 'Designer Name',
        type: 'text',
        text: 'MARCUS VANCE',
        fontFamily: "'Playfair Display', serif",
        fontSize: 100,
        fontWeight: 900,
        textAlign: 'left',
        letterSpacing: -2,
        lineHeight: 0.95,
        color: '#ffffff',
        x: 150,
        y: 320,
        width: 1200,
        height: 120,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-46-role',
        name: 'Discipline',
        type: 'text',
        text: 'CREATIVE DIRECTOR & BRAND ARCHITECT • SELECTED WORKS 2024-2027',
        fontFamily: "'Space Grotesk', sans-serif",
        fontSize: 22,
        fontWeight: 500,
        textAlign: 'left',
        letterSpacing: 3,
        lineHeight: 1.4,
        color: '#9ca3af',
        x: 150,
        y: 470,
        width: 1200,
        height: 50,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 47 — Personal Brand Poster
  {
    id: 'tpl-47',
    title: 'Personal Brand Poster',
    category: 'portfolio',
    tags: ['Portfolio', 'Brand', 'Poster'],
    width: 1200,
    height: 1600,
    background: {
      type: 'dark-luxury',
      color: '#0a0a0f',
    },
    elements: [
      {
        id: 'el-47-title',
        name: 'Brand Motto',
        type: 'text',
        text: 'UNAPOLOGETICALLY ORIGINAL',
        fontFamily: "'Cinzel', serif",
        fontSize: 66,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 6,
        lineHeight: 1.2,
        color: '#ffffff',
        x: 80,
        y: 240,
        width: 1040,
        height: 160,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 48 — Modern Abstract Poster
  {
    id: 'tpl-48',
    title: 'Modern Abstract Poster',
    category: 'poster',
    tags: ['Poster', 'Abstract', 'Minimalist'],
    width: 1200,
    height: 1600,
    background: {
      type: 'mesh',
      color: '#08080c',
      secondaryColor: '#4f46e5',
      accentColor: '#ec4899',
      tertiaryColor: '#06b6d4',
    },
    elements: [
      {
        id: 'el-48-title',
        name: 'Art Title',
        type: 'text',
        text: 'CHROMATIC DISSONANCE',
        fontFamily: "'Syne', sans-serif",
        fontSize: 78,
        fontWeight: 800,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1.1,
        color: '#ffffff',
        x: 80,
        y: 200,
        width: 1040,
        height: 170,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 49 — Cyberpunk Creative Poster
  {
    id: 'tpl-49',
    title: 'Cyberpunk Creative Poster',
    category: 'technology',
    tags: ['Technology', 'Cyberpunk', 'Poster'],
    width: 1200,
    height: 1600,
    isTrending: true,
    background: {
      type: 'neon',
      color: '#06070d',
    },
    elements: [
      {
        id: 'el-49-img',
        name: 'Tokyo Cyberpunk Alley',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80',
        x: 80,
        y: 240,
        width: 1040,
        height: 850,
        rotation: 0,
        opacity: 0.92,
        zIndex: 1,
        locked: false,
        hidden: false,
        objectFit: 'cover',
        flipX: false,
        flipY: false,
        borderRadius: 24,
        filters: { brightness: 105, contrast: 125, saturation: 130, blur: 0, grayscale: 0, duotoneEnabled: false },
      },
      {
        id: 'el-49-title',
        name: 'Cyberpunk Header',
        type: 'text',
        text: 'NEO SHINJUKU 2099',
        fontFamily: "'Syne', sans-serif",
        fontSize: 84,
        fontWeight: 800,
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1,
        color: '#00f2fe',
        x: 50,
        y: 110,
        width: 1100,
        height: 95,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
    ],
  },

  // 50 — Premium Black & Red Campaign
  {
    id: 'tpl-50',
    title: 'Premium Black & Red Campaign',
    category: 'luxury-brand',
    tags: ['Luxury Brand', 'Poster', 'Exclusive'],
    width: 1200,
    height: 1600,
    isPremium: true,
    isTrending: true,
    background: {
      type: 'solid',
      color: '#070709',
    },
    elements: [
      {
        id: 'el-50-shape',
        name: 'Crimson Slash',
        type: 'shape',
        shapeType: 'rectangle',
        x: 100,
        y: 100,
        width: 1000,
        height: 1400,
        rotation: 0,
        opacity: 0.85,
        zIndex: 1,
        locked: false,
        hidden: false,
        fill: '#120c10',
        strokeColor: '#e50914',
        strokeWidth: 3,
        borderRadius: 24,
      },
      {
        id: 'el-50-title',
        name: 'Red Flagship Title',
        type: 'text',
        text: 'THE CRIMSON EDITION',
        fontFamily: "'Cinzel', serif",
        fontSize: 70,
        fontWeight: 900,
        textAlign: 'center',
        letterSpacing: 6,
        lineHeight: 1.15,
        color: '#ffffff',
        x: 100,
        y: 240,
        width: 1000,
        height: 160,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'el-50-pill',
        name: 'Red Pill',
        type: 'shape',
        shapeType: 'pill',
        x: 450,
        y: 1220,
        width: 300,
        height: 60,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        locked: false,
        hidden: false,
        fill: '#e50914',
      },
      {
        id: 'el-50-pill-text',
        name: 'Pill Text',
        type: 'text',
        text: 'EXPLORE BESPOKE',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 16,
        fontWeight: 700,
        textAlign: 'center',
        letterSpacing: 3,
        lineHeight: 1,
        color: '#ffffff',
        x: 450,
        y: 1242,
        width: 300,
        height: 30,
        rotation: 0,
        opacity: 1,
        zIndex: 4,
        locked: false,
        hidden: false,
      },
    ],
  },
];

// Helper to instantiate a new editable Project from a Template
export function createProjectFromTemplate(template: Template): import('../types/canvas').Project {
  return {
    id: `proj_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
    title: `${template.title}`,
    category: template.category,
    width: template.width,
    height: template.height,
    background: JSON.parse(JSON.stringify(template.background)),
    elements: JSON.parse(JSON.stringify(template.elements)),
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isFavorite: false,
  };
}
