import { CanvasPreset } from '../types/canvas';

export const CANVAS_PRESETS: CanvasPreset[] = [
  {
    id: 'ig-post',
    name: 'Instagram Post',
    category: 'Social Media',
    width: 1080,
    height: 1080,
    iconName: 'Instagram',
    popular: true,
  },
  {
    id: 'ig-story',
    name: 'Instagram Story',
    category: 'Social Media',
    width: 1080,
    height: 1920,
    iconName: 'Smartphone',
    popular: true,
  },
  {
    id: 'yt-thumb',
    name: 'YouTube Thumbnail',
    category: 'Video',
    width: 1280,
    height: 720,
    iconName: 'Youtube',
    popular: true,
  },
  {
    id: 'presentation',
    name: 'Presentation (16:9)',
    category: 'Business',
    width: 1920,
    height: 1080,
    iconName: 'Presentation',
    popular: true,
  },
  {
    id: 'poster',
    name: 'Poster',
    category: 'Print',
    width: 1200,
    height: 1600,
    iconName: 'Image',
    popular: true,
  },
  {
    id: 'yt-banner',
    name: 'YouTube Banner',
    category: 'Video',
    width: 2560,
    height: 1440,
    iconName: 'Tv',
  },
  {
    id: 'fb-post',
    name: 'Facebook Post',
    category: 'Social Media',
    width: 1200,
    height: 630,
    iconName: 'Share2',
  },
  {
    id: 'tiktok',
    name: 'TikTok Video Cover',
    category: 'Social Media',
    width: 1080,
    height: 1920,
    iconName: 'Video',
  },
  {
    id: 'a4',
    name: 'A4 Document',
    category: 'Print',
    width: 1240,
    height: 1754,
    iconName: 'FileText',
  },
  {
    id: 'flyer',
    name: 'Marketing Flyer',
    category: 'Print',
    width: 1275,
    height: 1650,
    iconName: 'File',
  },
  {
    id: 'biz-card',
    name: 'Business Card',
    category: 'Business',
    width: 1050,
    height: 600,
    iconName: 'CreditCard',
  },
  {
    id: 'album-cover',
    name: 'Album Cover',
    category: 'Music',
    width: 1400,
    height: 1400,
    iconName: 'Disc',
  },
  {
    id: 'wallpaper',
    name: '4K Desktop Wallpaper',
    category: 'Screen',
    width: 2560,
    height: 1440,
    iconName: 'Monitor',
  },
];
